apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "nvidia-cloudwatch.fullname" . }}
  labels:
    {{- include "nvidia-cloudwatch.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "nvidia-cloudwatch.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nvidia-cloudwatch.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "nvidia-cloudwatch.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PERIOD
              value: "60"
            {{- if .Values.aws.region }}
            - name: AWS_REGION
              value: {{ .Values.aws.region }}
            {{- end }}
            {{- if .Values.aws.accessKeyId }}
            - name: AWS_ACCESS_KEY_ID
              value: {{ .Values.aws.accessKeyId }}
            {{- end }}
            {{- if .Values.aws.secretAccessKey }}
            - name: AWS_SECRET_ACCESS_KEY
              value: {{ .Values.aws.secretAccessKey }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
